name: Template

on: [push]        

jobs:
  default:
    name: Best Practice
    runs-on: windows-latest     
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: yarn
    - name: Run Prettier to Check Code Format
      run: .\node_modules\.bin\prettier --check src/**/*.{js,jsx}
    - name: Run Eslint to Check Lint Issues
      run: .\node_modules\.bin\eslint src/scripts/**/*.{js,jsx}
